CREATE TABLE IF NOT EXISTS `form_ne108` (

    id bigint(20) NOT NULL auto_increment,
    date datetime default NULL,
    pid bigint(20) default NULL,
    user varchar(255) default NULL,
    groupname varchar(255) default NULL,
    authorized tinyint(4) default NULL,
    activity tinyint(4) default NULL,

    
    `cctext` 			varchar(255) default NULL,
    `hpi` 				longtext default NULL,            
    `duration`			varchar(10) default NULL,           
    `duration2`			varchar(30) default NULL,   
    `durtext`			varchar(255) default NULL,   
    `quality`			varchar(30) default NULL,  
    `quatext`			varchar(30) default NULL,   
    `severity`			varchar(10) default NULL,
	`sizetext`			varchar(15) default NULL,
	`sizetext2` 		varchar(15) default NULL,  
	`sizetext3` 		varchar(15) default NULL,
	`sevtext`			varchar(255) default NULL,
	`orientation` 		varchar(30) default NULL,
	`orientation2` 		varchar(30) default NULL,
	`orientation3` 		varchar(30) default NULL, 
	`orientation4` 		varchar(30) default NULL, 
	`orientation5` 		varchar(30) default NULL, 
	`physicallocation` 	varchar(30) default NULL,   
	`loctext` 			varchar(255) default NULL,   
	`timing` 			varchar(30) default NULL,   
	`timtext` 			varchar(255) default NULL,   
	`modifyingfactors` 	varchar(30) default NULL,   
	`modtext` 			varchar(255) default NULL,   
	`associatedsigns` 	varchar(30) default NULL,   
	`associatedsigns2` 	varchar(30) default NULL,   
	`assoctext` 		varchar(255) default NULL,   
	`contexthpi` 		longtext default NULL,   
	
	`health` 			varchar(30) default NULL,   
    `weight` 			varchar(30) default NULL,   
    `fever` 			varchar(30) default NULL,   
    `chill` 			varchar(30) default NULL,   
    `mental` 			varchar(30) default NULL,   
    `insomnia` 			varchar(30) default NULL, 
    `appetite` 			varchar(30) default NULL, 
    `vision` 			varchar(30) default NULL,   
    `diplopia` 			varchar(30) default NULL,   
	`blurred` 			varchar(30) default NULL,
	`fugax` 			varchar(30) default NULL,
    `hearing` 			varchar(30) default NULL,   
    `tinnitus` 			varchar(30) default NULL,  
	`otalgia` 			varchar(30) default NULL,
	`otorrhea` 			varchar(30) default NULL,
    `head` 				varchar(30) default NULL,   
    `nose` 				varchar(30) default NULL,
    `epistaxis` 		varchar(30) default NULL,
	`rhinorrhea` 		varchar(30) default NULL,
	`rhinitis` 			varchar(30) default NULL,
    `lymph` 			varchar(30) default NULL,
    `cough` 			varchar(30) default NULL,
    `hemoptysis` 		varchar(30) default NULL,
	`purulentcough` 	varchar(30) default NULL,
    `sob` 				varchar(50) default NULL,
    `cp` 				varchar(30) default NULL,
    `orthopnea` 		varchar(30) default NULL,
    `pnd` 				varchar(50) default NULL,
    `doe` 				varchar(30) default NULL,
    `pvd` 				varchar(50) default NULL,
    `edema` 			varchar(30) default NULL,
    `valve` 			varchar(30) default NULL,
    `abdpain` 			varchar(30) default NULL,
    `nausea` 			varchar(30) default NULL,
    `vomiting` 			varchar(30) default NULL,
    `dysphagia` 		varchar(30) default NULL,
    `hematemesis` 		varchar(30) default NULL,
    `diarrhea` 			varchar(30) default NULL,
    `constipation` 		varchar(30) default NULL,
    `hematochezia` 		varchar(30) default NULL,
	`melena` 			varchar(30) default NULL,
    `dysuria` 			varchar(30) default NULL,
    `hematuria` 		varchar(30) default NULL,
    `discharge` 		varchar(30) default NULL,
    `hesistancy` 		varchar(30) default NULL,
    `breastmass` 		varchar(30) default NULL,
    `nippledischarge` 	varchar(30) default NULL,
    `bloodynipple` 		varchar(30) default NULL,
	`clearnipple` 		varchar(30) default NULL,
	`greennipple` 		varchar(30) default NULL,
    `breastpain` 		varchar(30) default NULL,
    `urine` 			varchar(30) default NULL,
    `drink` 			varchar(30) default NULL,
    `skinhair` 			varchar(30) default NULL,
    `heat` 				varchar(30) default NULL,
    `jtpain` 			varchar(30) default NULL,
    `jtswelling` 		varchar(30) default NULL,
    `arthritis` 		varchar(30) default NULL,
    `myalgia` 			varchar(30) default NULL,
    `neckms` 			varchar(30) default NULL,
    `upperbackms` 		varchar(30) default NULL,
    `lowerbackms` 		varchar(30) default NULL,
    `shouldersms` 		varchar(30) default NULL,
    `armsms` 			varchar(30) default NULL,
	`elbowms` 			varchar(30) default NULL,
    `wristms` 			varchar(30) default NULL,
    `handsms` 			varchar(30) default NULL,
	`fingersms` 		varchar(30) default NULL,
    `hipsms` 			varchar(30) default NULL,
    `legsms` 			varchar(30) default NULL,
	`kneems` 			varchar(30) default NULL,
	`anklems` 			varchar(30) default NULL,
    `feetms` 			varchar(30) default NULL,
	`toems` 			varchar(30) default NULL,
	`weakms` 			varchar(30) default NULL,
	`weakneckms` 		varchar(30) default NULL,
	`weakupperbackms` 	varchar(30) default NULL,
	`weaklowerbackms` 	varchar(30) default NULL,
	`weakshouldersms` 	varchar(30) default NULL,
	`weakarmsms` 		varchar(30) default NULL,
	`weakelbowms` 		varchar(30) default NULL,
	`weakwristms` 		varchar(30) default NULL,
	`weakhandsms` 		varchar(30) default NULL,
	`weakfingersms` 	varchar(30) default NULL,
	`weakhipsms` 		varchar(30) default NULL,
	`weaklegsms` 		varchar(30) default NULL,
	`weakkneems` 		varchar(30) default NULL,
	`weakanklems` 		varchar(30) default NULL,
	`weakfeetms` 		varchar(30) default NULL,
	`weaktoems` 		varchar(30) default NULL,
	`numbms` 			varchar(30) default NULL,
	`numbneckms` 		varchar(30) default NULL,
	`numbupperbackms` 	varchar(30) default NULL,
	`numblowerbackms` 	varchar(30) default NULL,
	`numbshouldersms` 	varchar(30) default NULL,
	`numbarmsms` 		varchar(30) default NULL,
	`numbelbowms` 		varchar(30) default NULL,
	`numbwristms` 		varchar(30) default NULL,
	`numbhandsms` 		varchar(30) default NULL,
	`numbfingersms` 	varchar(30) default NULL,
	`numbhipsms` 		varchar(30) default NULL,
	`numblegsms` 		varchar(30) default NULL,
	`numbkneems` 		varchar(30) default NULL,
	`numbanklems` 		varchar(30) default NULL,
	`numbfeetms` 		varchar(30) default NULL,
	`numbtoems` 		varchar(30) default NULL,
	`otherms` 			longtext default NULL,
    
    `bruising` 			varchar(30) default NULL,
    `lymphadenopathy` 	varchar(30) default NULL,
    `locationrashes` 	varchar(30) default NULL,
    `locationmoles` 	varchar(30) default NULL,
    `softtissue` 		varchar(30) default NULL,
    `massmobile` 		varchar(30) default NULL,
    `masshard` 			varchar(30) default NULL,
    `skinlymph` 		longtext default NULL,
    
    `weakness` 			varchar(30) default NULL,
    `seizures` 			varchar(30) default NULL,
    `memorychange` 		varchar(30) default NULL,
    `depression` 		varchar(30) default NULL,
    `rosfinal` 			varchar(100) default NULL,
    `rosfinal2` 		varchar(100) default NULL,
    
    `GA` 				varchar(30) default NULL,
    `vs` 				varchar(30) default NULL,
    `temptext` 			varchar(10) default NULL,
    `bptext` 			varchar(10) default NULL,
    `hrtext` 			varchar(10) default NULL,
    `rrtext` 			varchar(10) default NULL,
    `sattext` 			varchar(10) default NULL,
    
    `lymphadenopathype` varchar(30) default NULL,
    `lymphtext` 		longtext default NULL,
     
    `locationscarspe` 	varchar(30) default NULL,
    `scartext` 			longtext default NULL,
    
    `locationrashespe` 	varchar(30) default NULL,
    `rashtext` 			longtext default NULL,
    
    `locationmolespe` 	varchar(30) default NULL,
	`moletext` 			longtext default NULL,
    
    `softtissuepe` 		varchar(30) default NULL,
	`softtext` 			longtext default NULL,
       
    `bruisingpe` 		varchar(30) default NULL,
    `ecchymosistext` 	longtext default NULL,
    
    `head1` 			varchar(100) default NULL,
    `bruise` 			varchar(30) default NULL,
	`stepoff` 			varchar(30) default NULL,
	`scalpmass` 		varchar(30) default NULL,
	`facialmass` 		varchar(30) default NULL,
    
    `eyes1` 			varchar(30) default NULL,
    `papilledema` 		varchar(30) default NULL,
    `hemorrhages` 		varchar(30) default NULL,
    `exudates` 			varchar(30) default NULL,
    `scleralicterus` 	varchar(30) default NULL,
    `ptosis` 			varchar(30) default NULL,
    
	`ears1` 			varchar(100) default NULL,
    `eartext`	 		varchar(30) default NULL,
    `acuity` 			varchar(30) default NULL,
    `eardischarge` 		varchar(30) default NULL,
    
	`ears2` 			varchar(200) default NULL,
    `tmdull` 			varchar(30) default NULL,
    `tminjected` 		varchar(30) default NULL,
    `tmbulging` 		varchar(30) default NULL,
    
    `nose1` 			varchar(200) default NULL,
    `nosetext` 			varchar(30) default NULL,
    `epistaxispe` 		varchar(30) default NULL,
	`nasaldischarge` 	varchar(30) default NULL,
    
    `mt1` 				varchar(200) default NULL,
    `mtdry` 			varchar(30) default NULL,
    `mtlesion` 			varchar(30) default NULL,
    `mtlesion2` 		varchar(30) default NULL,
    `mttonsils` 		varchar(30) default NULL,
    `mtdentition` 		varchar(30) default NULL,
    `mtdentures` 		varchar(30) default NULL,
    `mtfb` 				varchar(30) default NULL,
	`mttext` 			varchar(100) default NULL,
    
    `jvd` 				varchar(200) default NULL,
    `thyromegaly` 		varchar(30) default NULL,
    `necklymph` 		varchar(30) default NULL,
    `neckmass` 			varchar(30) default NULL,
    `bruit` 			varchar(30) default NULL,
    
    `ausc` 				varchar(200) default NULL,
    `chestrales` 		varchar(30) default NULL,
    `chestrhonchi` 		varchar(30) default NULL,
    `chestbs` 			varchar(30) default NULL,
    
    `heartsounds` 		varchar(30) default NULL,
    `heartextra2` 		varchar(30) default NULL,
    `heartmurmurs` 		varchar(30) default NULL,
    `heartmurmurs2` 	varchar(30) default NULL,
    `heartrubs` 		varchar(30) default NULL,
    `heartrate` 		varchar(30) default NULL,
    
    `breastdimp` 		varchar(30) default NULL,
    `breastdimpling1` 	varchar(30) default NULL,
    `breasttender` 		varchar(30) default NULL,
    `breasttender1` 	varchar(30) default NULL,
    `breastdischarge` 	varchar(30) default NULL,
    `breastdischarge1` 	varchar(30) default NULL,
    `breastaxmass` 		varchar(30) default NULL,
    `breastaxmass1` 	varchar(30) default NULL,
    `breastaxmass2` 	varchar(30) default NULL,
    `breastaxmass3` 	varchar(30) default NULL,
    `rbreastdimp` 		varchar(30) default NULL,
    `rbreastdimpling1` 	varchar(30) default NULL,
    `rbreasttender` 	varchar(30) default NULL,
    `rbreasttender1` 	varchar(30) default NULL,
    `rbreastdischarge` 	varchar(30) default NULL,
    `rbreastdischarge1` varchar(30) default NULL,
    `rbreastaxmass` 	varchar(30) default NULL,
    `rbreastaxmass1` 	varchar(30) default NULL,
    `rbreastaxmass2` 	varchar(30) default NULL,
    `rbreastaxmass3` 	varchar(30) default NULL,
    
    `abdcontour` 		varchar(30) default NULL,
    `abdtender` 		varchar(30) default NULL,
    `abdtender2` 		varchar(30) default NULL,
    `abdtender3`	 	varchar(30) default NULL,
    `abdtender4` 		varchar(30) default NULL,
    `abdtender5` 		varchar(30) default NULL,
    `abdtender6` 		varchar(30) default NULL,
    `abdhernia` 		varchar(30) default NULL,
    `abdhernia2` 		varchar(30) default NULL,
    `abdhernia3` 		varchar(30) default NULL,
    `abdhernia4` 		varchar(30) default NULL,
    `abdhernia5` 		varchar(30) default NULL,
    `abdhernia6` 		varchar(30) default NULL,
    `abdhsm` 			varchar(30) default NULL,
    `abdguard` 			varchar(30) default NULL,
    `abdrebound` 		varchar(30) default NULL,
    `abdscar` 			varchar(30) default NULL,
    `abdbs` 			varchar(30) default NULL,
    `abdbruit` 			varchar(30) default NULL,
    `guaiac` 			varchar(30) default NULL,
    `rectalmass` 		varchar(30) default NULL,
    `rectalmass2` 		varchar(30) default NULL,
    `rectalfissure` 	varchar(30) default NULL,
    `rectalfissure2` 	varchar(30) default NULL,
    `rectalhemor` 		varchar(30) default NULL,
    `rectalhemor2` 		varchar(30) default NULL,
    `rectalsph` 		varchar(30) default NULL,
    `guingmass` 		varchar(30) default NULL,
    `guingmass2` 		varchar(30) default NULL,
    `guscromass` 		varchar(30) default NULL,
    `guscromass2` 		varchar(30) default NULL,
    `guvarico` 			varchar(30) default NULL,
    `extcya` 			varchar(30) default NULL,
    `extclub` 			varchar(30) default NULL,
    `extedem` 			varchar(30) default NULL,
    `extedem2` 			varchar(30) default NULL,
    `extrom` 			varchar(100) default NULL,
    `extlue` 			varchar(30) default NULL,
    `extrue` 			varchar(30) default NULL,
    `extlle` 			varchar(30) default NULL,
    `extrle` 			varchar(30) default NULL,
	
    `vascaaa` 			varchar(50) default NULL,
    `vascradL` 			varchar(50) default NULL,
    `vascradR` 			varchar(50) default NULL,
    `vascfemL` 			varchar(50) default NULL,
    `vascfemR` 			varchar(50) default NULL,
    `vascpopL` 			varchar(50) default NULL,
    `vascpopR` 			varchar(50) default NULL,
    `vascdpL` 			varchar(50) default NULL,
    `vascdpR` 			varchar(50) default NULL,
    `vascptL` 			varchar(50) default NULL,
    `vascptR` 			varchar(50) default NULL,
	
    `neurolat` 			varchar(50) default NULL,
    `neuronumb` 		varchar(30) default NULL,
    `neuroweak` 		varchar(30) default NULL,
    `neuroRUE` 			varchar(30) default NULL,
    `neuroRLE` 			varchar(30) default NULL,
    `neuroLUE` 			varchar(30) default NULL,
    `neuroLLE` 			varchar(30) default NULL,
    
    `endassess` 		longtext default NULL,
    `endplan` 			longtext default NULL,
    
    `risks2` 			varchar(70) default NULL,
    `risks3` 			varchar(50) default NULL,
    `risks4` 			varchar(50) default NULL,
    `risks5` 			varchar(50) default NULL,
    `risks6` 			varchar(50) default NULL,
    `risks7` 			varchar(50) default NULL,
    `risks8` 			varchar(50) default NULL,
    `risks9` 			varchar(50) default NULL,
    `risks10` 			varchar(50) default NULL,
    `risks11` 			varchar(50) default NULL,
    `risks12` 			varchar(50) default NULL,
    `risks13` 			varchar(50) default NULL,
    `risks14` 			varchar(50) default NULL,
    `risks15` 			varchar(50) default NULL,
    `risks16` 			varchar(50) default NULL,
    `risks17` 			varchar(50) default NULL,
    `risks18` 			varchar(50) default NULL,
    `risks19` 			varchar(50) default NULL,
    `risks20` 			varchar(50) default NULL,
    `risks21` 			varchar(70) default NULL,
    `risks22` 			varchar(50) default NULL,
    `risks23` 			varchar(50) default NULL,
    `risks24` 			varchar(50) default NULL,
    
    `risksanes` 		longtext default NULL,
    
    `lasertx1` 			varchar(255) default NULL,
    `lasertx2` 			longtext default NULL,
    
    `weighthm` 			varchar(160) default NULL,
    `weighthmtime` 		varchar(50) default NULL,
    `smokinghm` 		varchar(130) default NULL,
    `smokinghmtime` 	varchar(50) default NULL,
    
    `followup` 			varchar(30) default NULL,
    `followup1` 		varchar(10) default NULL,
    `followup2` 		varchar(10) default NULL,
        
    `sig` char(1),  
    `sig_date` datetime default NULL,

     PRIMARY KEY (id)
) 
